version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependabot
      - actions
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    labels:
      - dependabot
      - npm
    schedule:
      interval: monthly
    groups:
      vitest:
        patterns:
          - vitest
          - "@vitest/*"
      mime-types:
        patterns:
          - mime-types
          - "@types/mime-types"
      oxc:
        patterns:
          - oxfmt
          - oxlint
