name: spa-deploy-action
description: deploy your spa with corret cache-control
author: islishude <islishude@gmail.com>
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  dir-path:
    description: directory path for deploying
    required: true
  s3-bucket:
    description: aws s3 bucket name
    required: true
  s3-bucket-prefix:
    description: aws S3 bucket prefix
  delete:
    description: files that exist in the s3 but not in the local are deleted.
    default: 'true'
  cache-control:
    description: file glob and cache control directive pairs
    default: '{}'
  cache-control-merge-policy:
    description: 'used for merge built-in and your custom cache-control'
    default: 'upsert'
    required: true
  default-cache-control:
    description: use if no cache control globbing matched

runs:
  using: node24
  main: dist/index.js
